### ISSUE TITLE
failed to select a version

### ISSUE THREAD

**Issue by slyons** [Devolutions/mongodb-cwal-rs#15]
Trying to start a project with the latest version and I'm running into the following build error:

```shell
error: failed to select a version for the requirement `crypto-mac = "^0.6"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
location searched: crates.io index
required by package `hmac v0.6.2`
    ... which is depended on by `mongodb_cwal v0.6.7`
    ... which is depended on by `mongo-file-center v0.5.0`
    ... which is depended on by ...
```

Looks like crypto-mac 0.6 is no longer available, so a few dependencies may need to be updated.

**Comment by fdubois1** [comment]
Hi @slyons ,

This is an old project. At that time, mongodb had was not production ready and we fixed a few issue by ourself. But now, mongodb team took ownership and you should consider to use https://crates.io/crates/mongodb instead of that project.  They release a version 1 many months ago and they are working on version 2, beta is available : https://github.com/mongodb/mongo-rust-driver

If it can help, we added a layer on top of it that you can find here : https://crates.io/crates/mongodm (https://github.com/Devolutions/mongodm-rs)

Best regards

**Comment by slyons** [comment]
Thanks!
